version: 2.1

orbs:
  maven:  circleci/maven@1.0.3
  node:   circleci/node@4.1.0
    
workflows:
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: './BackEnd'
          test_results_path: './BackEnd/target/surefire-reports'
  react_test:
    jobs:
      - node/test:
          app-dir: './FrontEnd'